# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      ci:
        patterns:
          - "*"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/metascraper" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      build:
        patterns:
          - "*"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/test" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      build:
        patterns:
          - "*"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/terraform" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      ci:
        patterns:
          - "*"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      build:
        patterns:
          - "*"
