name: hugo

on:
  workflow_call:

jobs:
  hugo:
    name: build && hugo deploy
    runs-on: ubuntu-latest
    env:
      HUGO_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: metascraper/cache
          key: v1-${{ hashFiles('metascraper/yarn.lock') }}

      - name: Run build
        run: docker compose run hugo --

      - name: Run deploy
        run: docker compose run hugo deploy --maxDeletes -1
